# プラグインマネージャ
[[plugins]]
repo = 'Shougo/dein.vim'

# 補完
[[plugins]]
repo = 'Shougo/neocomplete.vim'

# 補完
[[plugins]]
repo = 'Shougo/neocomplcache'
on_i = 1
hook_add = 'source ~/.vim/dein/plugins/neocomplcache.vim'

[[plugins]]
repo = 'junegunn/fzf'
hook_add = 'source ~/.vim/dein/plugins/fzf.vim'

# "" や () をインサートし易くする
[[plugins]]
repo = 'tpope/vim-surround'

# スニペット
[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = 'source ~/.vim/dein/plugins/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# ディレクトリツリー表示
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.vim/dein/plugins/nerdtree.vim'

# ステータスバーの表示
[[plugins]]
repo = 'atsushi130/lightline.vim'
rev  = 'master'
hook_add = 'source ~/.vim/dein/plugins/lightline.vim'

# 構文チェックプラグイン
[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = 'source ~/.vim/dein/plugins/syntastic.vim'

# 閉じ括弧の自動挿入
[[plugins]]
repo = 'kana/vim-smartinput'

# ES6 のシンタックスハイライト
[[plugins]]
repo = 'pangloss/vim-javascript'

# JSX のシンタックスハイライト
[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript', 'html']
hook_add = 'source ~/.vim/dein/plugins/vim-js-indent.vim'

# TypeScript のファイルタイプ検出
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

# TypeScript のシンタックスチェック
[[plugins]]
repo = 'Quramy/tsuquyomi'
hook_add = 'source ~/.vim/dein/plugins/tsuquyomi.vim'

# Rust のシンタックスチェック
[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = 'source ~/.vim/dein/plugins/rust.vim'

# tags自動更新
[[plugins]]
repo = 'szw/vim-tags'

# tagbar メソッドリスト
[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = 'source ~/.vim/dein/plugins/tagbar.vim'

# 異なるエディタで設定を共有
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# Markdown プラグイン
[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = 'source ~/.vim/dein/plugins/vim-markdown.vim'

# Markdown プレビュー
[[plugins]]
repo = 'kannokanno/previm'
hook_add = 'source ~/.vim/dein/plugins/previm.vim'

# ブラウザ自動同期
[[plugins]]
repo = 'tyru/open-browser.vim'

# 置換いい感じ
[[plugins]]
repo = 'osyo-manga/vim-over'
hook_add = 'source ~/.vim/dein/plugins/vim-over.vim'

[[plugins]]
repo = 'vim-scripts/dbext.vim'
hook_add = 'source ~/.vim/dein/plugins/dbext.vim'
