let dbext_default_profile=""
let dbext_default_type="PGSQL"
let dbext_default_user="username"
let dbext_default_passwd="password"
let dbext_default_dbname="dbname"
let dbext_default_host="host"
let dbext_default_port="port"
